package com.wesdom.compa.backend.dtos.views;

public class SystemViews {
    public static class GeneralView{};
    public static class AuthUserBasicView {};
    public static class ManufacturerBasicView{};
    public static class CommercialPartnerBasicView{};
    public static class PromoterBasicView{};
    public static class PromoterDetailedView {};
    public static class GroupBasicView{};
    public static class GroupDetailedView{};
    public static class EstateBasicView {};
    public static class EstateSegmentBasicView{};
    public static class EstateSegmentDetailView{};
    public static class ProductBasicView{};
    public static class ProductInStateBasicView{};
    public static class ProductionActivityBasicView{};
    public static class ProductionActivityAnswerBasicView{};
    public static class NearbyFloraBasicView {};
    public static class ExpertVisitBasicView {};
    public static class ExpertAlertBasicView {};
    public static class ExpertVisitNoteBasicView {};
    public static class LocationBasicView {};
    public static class ActivityBasicView {};
    public static class ActivityOptionBasicView {};
    public static class OptionAnswerBasicView {};
    public static class ProductionStageBasicView {};
    public static class AssociationBasicView {};
    public static class AssociationDetailedView {};
    public static class AssociationMemberBasicView {};
    public static class RequestBasicView {};
    public static class RequestOfferBasicView {};
    public static class RequestOfferDetailView {};
    public static class BioProductBasicView {};
    public static class BioProductDetailView {};
    public static class AdvertisingBasicView {};
    public static class ProductWorkBasicView {};
    public static class PostHarvestCheckBasicView {};
    public static class PackingOptionBasicView {};
}
